Args = --no-fallback \
       --enable-url-protocols=https \
       -H:+ReportExceptionStackTraces \
       -Djava.net.preferIPv4Stack=false \
       -Dfile.encoding=UTF-8 \
       -Dstdout.encoding=UTF-8 \
       -Dstderr.encoding=UTF-8
